with RANKED_SALES AS(
select "DATE" as "DATE_",
"SHOPNUMBER", "ID_GOOD",
SUM("QTY") as TOTAL_SALES,
ROW_NUMBER() OVER (PARTITION BY "DATE", "SHOPNUMBER" ORDER BY SUM("QTY") DESC) AS GOOD_RANK
FROM sales
group by "DATE", "SHOPNUMBER", "ID_GOOD"
)
select "DATE_", "SHOPNUMBER", "ID_GOOD" from RANKED_SALES
where GOOD_RANK<=3
order by 1,2,3

